project:
  type: book

book:
  title: "oc_cciea.github.io"
  author: "I. D. Schroeder"
  date: "11/9/2025"
  chapters:
    - index.qmd
    - part: "2024"
      chapters:
        - BasinScaleIndicators_2024.qmd
        - NPH_2024.qmd
        - SSTspatial_2024.qmd
        - MHW_2024.qmd
        - HCI_2024.qmd
        - DepthTimeTemp_2024.qmd
        - DepthTimeTempGlider_2024.qmd
        - bakunUI_2024.qmd
        - phenologyUI_2024.qmd
    - part: "2025"
      chapters:
        - BasinScaleIndicators_2025.qmd
        - NPH_2025.qmd
        - SSTspatial_2025.qmd
        - MHW_2025.qmd
        - HCI_2025.qmd
        - DepthTimeTemp_2025.qmd
        - DepthTimeTempGlider_2025.qmd
        - bakunUI_2025.qmd
        - phenologyUI_2025.qmd
        - DissolvedOxygen_2025.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
