name: Code 1, hci ROMS -- download NRT ROMS
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout


      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          channels: conda-forge,defaults
          python-version: 3.12
          # These properties enable the use of mamba, which is much faster and far less error
          # prone than conda while being completely compatible with the conda CLI
          use-mamba: true
          mamba-version: "*"	  

      - name: Install some packages
        # The `-l` is needed so conda environment activation works correctly
        shell: bash -l {0}
        run: |
          mamba install -c conda-forge numpy pandas scipy matplotlib xarray dask netCDF4 bottleneck requests cartopy seawater

      - name: set pythonpath
        run: |
          echo "PYTHONPATH=code_gha/fun_gha/" >> $GITHUB_ENV

      - name: download and subset NRT ROMS
        shell: bash -l {0}
        run: python code_gha/HCI_ROMS/nrt_roms_daily_update.py

      - name: Print dir tree and check disk space
        shell: bash {0}
        run: |
          tree
          df -h

      - name: git auto commit -- save distance to shore mask netcdf
        uses: stefanzweifel/git-auto-commit-action@v7
