name: Code 1 new UI -- Python Download CUTI&BEUTI and create IEA CSV

env:
  PYTHON_VERSION: "3.12"


on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          channels: conda-forge,defaults
          python-version: 3.12
          # These properties enable the use of mamba, which is much faster and far less error
          # prone than conda while being completely compatible with the conda CLI
          use-mamba: true
          mamba-version: "*"	  

      - name: Install some packages
        # The `-l` is needed so conda environment activation works correctly
        shell: bash -l {0}
        run: |
          mamba install -c conda-forge numpy pandas scipy matplotlib xarray dask netCDF4 bottleneck requests cartopy seawater

      - name: set pythonpath
        run: |
          echo "PYTHONPATH=code_gha/fun_gha/" >> $GITHUB_ENV

      - name: code3_newUI_gha, Run Python download data from Erddap
        shell: bash -l {0}      
        run: python code_gha/newUI/download_newUI_gha.py

      - name: code4_newUI_gha, Run Python create daily, monthly from 6 hr
        shell: bash -l {0}      
        run: python code_gha/newUI/create_daily_monthly_timeseries.py

      - name: Print dir tree and check disk space
        shell: bash {0}
        run: |
          tree
          df -h

      - name: code5_newUI_gha, Run Python save data to R style CSV Monthly
        shell: bash -l {0}      
        run: python code_gha/newUI/create_oc_newUI_M_std.py

      - name: code6_newUI_gha, Run Python save data to R style CSV Seasonal
        shell: bash -l {0}      
        run: python code_gha/newUI/create_oc_newUI_S_std.py

      - name: git auto commit
        uses: stefanzweifel/git-auto-commit-action@v7
